name: example
description: Example project for HOCR Editor.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  image: ^3.2.2
  dart_hocr: ^0.1.0
  hocr_editor:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/sample1.jpg
    - assets/sample1.hocr
    
